name = "811-ticket-serverless"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "811-tickets"
database_id = "00000000-0000-0000-0000-000000000001"

[assets]
directory = "../frontend"
binding = "ASSETS"

[triggers]
crons = ["0 * * * *"]
