name = "811-ticket-serverless"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "ayocollect-db"
database_id = "d1d567d9-a127-43f4-be24-1dd370928b48"

[assets]
directory = "../frontend"
binding = "ASSETS"

[triggers]
crons = ["0 * * * *"]
