name = "ayocollect"
main = "src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ayocollect-db"
database_id = "d1d567d9-a127-43f4-be24-1dd370928b48"

[[queues.producers]]
binding = "QUEUE"
queue = "ayocollect-queue"

[[queues.consumers]]
queue = "ayocollect-queue"
max_batch_size = 10
max_batch_timeout = 5

[triggers]
crons = ["0 7 * * *", "0 8 * * *"]

[vars]
SYNC_REGIONS = "NV,CA,DA"
ORG_CREATED_BY_FILTER = ""

[dev]
port = 8790
